<?php
/**
 * Непосредственно сам файл маршрутов проекта
 */
return array(
    'news/([0-9])' => 'news/index/$1',
    'news/([a-z]+)' => 'news/view/$1',
    'news' => 'news/index',
    'news/archive' => 'news/archive',
    'products/([a-z]+)' => 'products/views/$1',
    'products' => 'products/index',
    'register/do' => 'register/do',
    'register/activateAccount' => 'register/activate',
    'register/doActivate' => 'register/doActive',
    'register' => 'register/index',
    'login/doActive' => 'login/doActive',
    'login/logout' => 'login/logout',
    'login' => 'login/index',
    'cart/updateCart' => 'cart/updateOrder',
    'cart/orderNow' => 'cart/orderNow',
    'cart/delete/([0-9]+)' => 'cart/delete/$1',
    'cart/addSuperBuket' => 'cart/addSuperBuket',
    'cart/add/([0-9]+)' => 'cart/add/$1',
    'cart/addResponse/([0-9]+)' => 'cart/addResponse/$1',
    'cart/checkout' => 'cart/checkout',
    'cart' => 'cart/index',
    'service/deliver' => 'service/deliver',
    'service/pay-methods' => 'service/payment',
    'service/zakaz' => 'service/zakaz',
    'catalog/product/([0-9-a-z]+)' => 'category/product/$1',
    'catalog/([0-9-a-z]+)' => 'category/catname/$1',
    'contacts/momentView' => 'contacts/momentView',
    'contacts/post_data' => 'contacts/postM',
    'contacts' => 'contacts/index',
    'cridenshial-politic' => 'politic/index',
    'events' => 'events/index',
    'flower_job' => 'flowersJob/gallery',
    'UserRoom/presonalUnlock' => 'user/hiSkidka',
    'UserRoom/historyPayment' => 'user/Payment',
    'UserRoom/updatePro' => 'user/updatePro',
    'UserRoom/editProfile' => 'user/profileEdit',
    'UserRoom' => 'user/room',
    'reviews' => 'reviews/index',
    'cpUser/updateUser/([0-9]+)' => 'cpUser/update/$1',
    'cpUser/edit/([0-9]+)' => 'cpUser/edit/$1',
    'cpUser' => 'cpUser/index',
    'cpAllSell/editOrder/([0-9]+)' => 'cpAllSell/edit/$1',
    'cpAllSell/viewMoment/([0-9]+)' => 'cpAllSell/viewMoment/$1',
    'cpAllSell' => 'cpAllSell/index',
    'cpProducts/updateAdd' => 'cpProducts/updateAdd',
    'cpProducts/add' => 'cpProducts/add',
    'cpProducts' => 'cpProducts/index',
    'partner/view_company/([a-z]+)' => 'partner/company/$1',
    'partner' => 'partner/index',
    'cp' => 'cp/isAdmin',
    'search-buket/resultMoment' => 'search/resData',
    'search-buket' => 'search/index',
    'karta-sayta' => 'kartaSite/index',
    'calc-buket-once' => 'calcBuket/index',
    'comment/postData' => 'comment/postData',
    '' => 'index/home',
    'comment/commentProduct/([0-9]+)' => 'comment/commentProduct/$1',
);
